# Generated by Django 5.2.6 on 2025-10-16 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_lostfounditem_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('floor', models.PositiveSmallIntegerField(choices=[(1, '1 Floor'), (2, '2 Floor'), (3, '3 Floor'), (4, '4 Floor'), (5, '5 Floor'), (6, '6 Floor'), (7, '7 Floor')], default=1)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('creator_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=16)),
                ('creator_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('floor', models.PositiveSmallIntegerField(choices=[(1, '1 Floor'), (2, '2 Floor'), (3, '3 Floor'), (4, '4 Floor'), (5, '5 Floor'), (6, '6 Floor'), (7, '7 Floor')], default=1)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('creator_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=16)),
                ('creator_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('name', 'creator_type', 'creator_id')},
            },
        ),
    ]
