# Generated by Django 5.2.6 on 2025-10-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_eventpin_savedlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpin',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='savedlocation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='eventpin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventpin',
            name='creator_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventpin',
            name='creator_type',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventpin',
            name='floor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventpin',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savedlocation',
            name='creator_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='savedlocation',
            name='creator_type',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedlocation',
            name='floor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='savedlocation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='savedlocation',
            name='created_at',
        ),
    ]
