# Generated by Django 5.2 on 2025-10-16 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_lostandfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_transition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='transition_type',
            field=models.CharField(blank=True, choices=[('corridor', 'Corridor'), ('stairs', 'Stairs'), ('elevator', 'Elevator')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='LocationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('transition_type', models.CharField(choices=[('corridor', 'Corridor'), ('stairs', 'Stairs'), ('elevator', 'Elevator')], default='corridor', max_length=20)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='login.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='login.location')),
            ],
            options={
                'unique_together': {('from_location', 'to_location')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='connections',
            field=models.ManyToManyField(related_name='connected_locations', through='login.LocationConnection', to='login.location'),
        ),
    ]
