# Generated by Django 5.2 on 2025-10-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_eventpin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lostfounditem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='claim',
            name='claimant_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lostfound_claims', to='login.teacher'),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Optional exact answer; if provided, matching claims auto-approve.', max_length=200),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='reporter_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_lostfound_items', to='login.teacher'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='login_claim_status_0e666a_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['created_at'], name='login_claim_created_f84215_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfounditem',
            index=models.Index(fields=['status'], name='login_lostf_status_5defb9_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfounditem',
            index=models.Index(fields=['created_at'], name='login_lostf_created_01f586_idx'),
        ),
    ]
