# Generated by Django 5.2 on 2025-10-17 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_claim_options_alter_lostfounditem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for claim')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='login.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'claimant')},
            },
        ),
    ]
