# Generated by Django 5.2 on 2025-10-17 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_productclaim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productclaim',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='productclaim',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productclaim',
            name='claimant_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.student'),
        ),
        migrations.AddField(
            model_name='productclaim',
            name='claimant_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.teacher'),
        ),
        migrations.AlterField(
            model_name='productclaim',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productclaim',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to='login.teacher'),
        ),
        migrations.AlterField(
            model_name='productclaim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.RemoveField(
            model_name='productclaim',
            name='claimant',
        ),
    ]
