# Generated by Django 5.2 on 2025-10-17 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_productclaim_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclaim',
            name='claimant_student',
        ),
        migrations.RemoveField(
            model_name='productclaim',
            name='claimant_teacher',
        ),
        migrations.RemoveField(
            model_name='productclaim',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productclaim',
            name='reviewed_by',
        ),
        migrations.AlterModelOptions(
            name='claim',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lostfounditem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='login_claim_status_0e666a_idx',
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='login_claim_created_f84215_idx',
        ),
        migrations.RemoveIndex(
            model_name='lostfounditem',
            name='login_lostf_status_5defb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='lostfounditem',
            name='login_lostf_created_01f586_idx',
        ),
        migrations.AlterField(
            model_name='claim',
            name='claimant_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_made', to='login.teacher'),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Optional exact answer; leave blank if staff will review manually.', max_length=200),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='reporter_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_items', to='login.teacher'),
        ),
        migrations.DeleteModel(
            name='ProductClaim',
        ),
    ]
